<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

/*
|-------------------------------------------------------------------------------
| Stateless API routes
|-------------------------------------------------------------------------------
|
| OWNED BY HANDOVER 01. DO NOT EDIT THIS FILE TO ADD AN ENDPOINT.
|
| This file is for token-authenticated, session-less clients. There are none
| yet, and the MVP is not expected to grow one.
|
| The application's own JSON endpoints do NOT belong here. The frontend is
| Inertia and authenticates with the session cookie, so its /api/v1 endpoints
| are declared in routes/features/<feature>.php with an `api/v1` prefix and run
| inside the `web` middleware group — they need session and CSRF, which this
| group deliberately does not have (docs/architecture.md §2, §3).
|
| Registering them here instead would mean adding Sanctum, CORS, and a second
| authentication path for a single-origin application: exactly the work Inertia
| was chosen to avoid.
|
*/

Route::prefix('v1')->name('api.stateless.v1.')->group(function (): void {
    //
});
