<?php

declare(strict_types=1);

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\Web\DashboardController;
use App\Http\Controllers\Web\HomeController;
use Illuminate\Support\Facades\Route;

/*
|-------------------------------------------------------------------------------
| Web routes
|-------------------------------------------------------------------------------
|
| OWNED BY HANDOVER 01. DO NOT EDIT THIS FILE TO ADD A FEATURE.
|
| routes/web.php and routes/api.php are the single worst merge conflict in a
| parallel Laravel build: every feature wants to append to them, so every
| feature conflicts with every other feature. Instead, drop your routes in
|
|     routes/features/<your-feature>.php
|
| and the loader at the bottom of this file picks them up. Files load in
| alphabetical order; nothing may depend on that order.
|
| Inside a feature file, apply your own middleware — the loader adds none, so
| a feature file is explicit about whether it is public, authenticated, or
| admin-only. See routes/features/README.md.
|
*/

Route::get('/', HomeController::class)->name('home');

Route::middleware('guest')->group(function (): void {
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store']);

    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store']);
});

Route::middleware('auth')->group(function (): void {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
});

require __DIR__.'/features.php';
