/**
 * Page-side types for progress, mastery and gamification.
 *
 * Mirrors `App\Http\Resources\Progress\*`. Ids are strings for the reason every
 * id in this codebase is (docs/architecture.md §5.4 rule 4): a 64-bit key does
 * not survive a JavaScript number, and nothing here does arithmetic on one.
 *
 * **Nothing here carries an answer key.** A `ProgressDto` is a summary of
 * answers already graded server-side; it names no question and no correct
 * option, and `ActivityEntryDto` deliberately carries a finished label rather
 * than the event payload, which records the outcome of graded attempts
 * (invariant 4).
 */

/** Mirrors App\Enums\TopicType. */
export type TopicType = 'structure' | 'organ' | 'system'

/** Mirrors App\Enums\MasteryFactor — the four multipliers in the formula. */
export type MasteryFactor = 'accuracy' | 'recency' | 'hint_reliance' | 'coverage'

/** Mirrors App\Enums\RecommendedActivity. */
export type RecommendedActivity = 'lesson' | 'quiz'

/**
 * Mirrors App\Enums\LearningEventType.
 *
 * `ClientEventType` is the subset a browser is allowed to assert. The server
 * rejects anything else from `POST /api/v1/events`, because everything else
 * feeds XP, a badge or a completion metric.
 */
export type ClientEventType =
  'organ_viewed' | 'structure_selected' | 'structure_isolated' | 'layer_changed'

export type LearningEventType =
  | ClientEventType
  | 'lesson_started'
  | 'lesson_completed'
  | 'question_answered'
  | 'mission_started'
  | 'mission_completed'
  | 'hint_requested'
  | 'ai_question_asked'
  | 'simulation_started'
  | 'simulation_completed'

/** What a client event may be about. Mirrors RecordEventsRequest. */
export type EventContextType = 'organ' | 'structure' | 'lesson'

/** One event, as the browser queues it before a flush. */
export interface ClientEvent {
  readonly type: ClientEventType
  readonly occurredAt: string
  readonly contextType?: EventContextType
  readonly contextId?: number
  readonly payload?: Readonly<Record<string, string>>
}

/** One row of PRD §15's per-system table. */
export interface SystemMasteryDto {
  readonly id: string
  readonly slug: string
  readonly name: string
  /** 0–100. */
  readonly score: number
  readonly attempts: number
  readonly correctAttempts: number
  readonly coveredStructures: number
  readonly totalStructures: number
  readonly lastActivityAt: string | null
}

/**
 * What to do next, and why.
 *
 * `reason` arrives as finished prose, templated server-side from the mastery
 * breakdown and never generated by the LLM (docs/architecture.md §10). The
 * page renders it; it does not compose it.
 */
export interface RecommendationDto {
  readonly organSlug: string
  readonly organName: string
  readonly activity: RecommendedActivity
  readonly activityLabel: string
  readonly title: string
  readonly href: string
  readonly reason: string
  readonly weakestFactor: MasteryFactor | null
  readonly score: number
}

/** One earned badge. Carries no criteria — see AchievementResource. */
export interface AchievementDto {
  readonly slug: string
  readonly name: string
  readonly description: string
  readonly icon: string
}

export interface ActivityEntryDto {
  readonly type: LearningEventType
  readonly label: string
  readonly occurredAt: string
}

export interface GamificationDto {
  readonly xp: number
  readonly level: number
  readonly xpIntoLevel: number
  readonly xpForLevel: number
  readonly streakDays: number
  readonly achievements: readonly AchievementDto[]
}

/** The whole dashboard payload. Mirrors ProgressSummaryResource. */
export interface ProgressDto {
  readonly overallScore: number
  readonly systems: readonly SystemMasteryDto[]
  readonly strongest: SystemMasteryDto | null
  readonly needsPractice: SystemMasteryDto | null
  readonly lessonsCompleted: number
  readonly quiz: {
    readonly attempts: number
    readonly correctAttempts: number
    readonly accuracyPercent: number
  }
  readonly gamification: GamificationDto
  readonly recentActivity: readonly ActivityEntryDto[]
  readonly recommendation: RecommendationDto | null
}
