<?php

declare(strict_types=1);

namespace App\Services\AI;

use App\Contracts\RetrievedChunk;

/**
 * What the tutor pipeline produced, before an API Resource shapes it.
 *
 * `sources` is empty until Handover 11 implements retrieval. `sourceNote` is
 * how the tutor *says so* rather than silently presenting an unsourced answer
 * as if it were cited (docs/architecture.md §8.2) — it is generated by this
 * application, not by the model, so the honesty of the claim does not depend on
 * the model having followed an instruction.
 */
final readonly class TutorReply
{
    /**
     * @param  list<string>  $followUpQuestions
     * @param  list<RetrievedChunk>  $sources
     * @param  string|null  $sourceNote  null once sources are cited
     */
    public function __construct(
        public string $answer,
        public array $followUpQuestions,
        public array $sources,
        public ?string $sourceNote,
        public int $conversationId,
    ) {}
}
