<?php

declare(strict_types=1);

use App\Models\AnatomicalStructure;
use App\Models\Organ;
use App\Models\User;

/*
| "No relevant sources — and saying so" (docs/architecture.md §8.2).
|
| Retrieval is Handover 11's. Until it lands, every answer is unsourced, and the
| tutor has to say which grounding it actually used rather than presenting an
| uncited answer as if it were cited (PRD §24). This path is built now precisely
| so Handover 11 inherits it instead of inventing it.
*/

beforeEach(function (): void {
    $this->actingAs(User::factory()->create());
});

it('says it used the curated notes when a structure is selected', function (): void {
    $organ = Organ::factory()->published()->create(['slug' => 'heart', 'name' => 'Heart']);
    $structure = AnatomicalStructure::factory()->published()->for($organ)->create([
        'name' => 'Left ventricle',
        'function' => 'Pumps oxygenated blood into the aorta.',
    ]);

    $response = $this->postJson('/api/v1/ai/tutor/ask', [
        'question' => 'Why is its wall thicker?',
        'structureId' => $structure->getKey(),
    ])->assertOk();

    expect($response->json('data.sources'))->toBe([])
        ->and($response->json('data.sourceNote'))
        ->toContain('No indexed source')
        ->toContain('Left ventricle')
        ->toContain('curated notes');
});

it('says it used general anatomy when nothing is selected', function (): void {
    $response = $this->postJson('/api/v1/ai/tutor/ask', ['question' => 'What is an artery?'])
        ->assertOk();

    expect($response->json('data.sourceNote'))
        ->toContain('No indexed source')
        ->toContain('well-established anatomy');
});

it('states the note itself rather than trusting the model to', function (): void {
    // The note is generated by this application, so the honesty of the claim
    // does not depend on the model having followed an instruction. NullProvider
    // echoes the prompt back and never writes a source note of its own.
    $response = $this->postJson('/api/v1/ai/tutor/ask', ['question' => 'What is an artery?'])
        ->assertOk();

    expect($response->json('data.answer'))->not->toContain('No indexed source')
        ->and($response->json('data.sourceNote'))->toContain('No indexed source');
});

it('records an empty source id list on the stored turn for Handover 11 to fill', function (): void {
    $conversationId = $this->postJson('/api/v1/ai/tutor/ask', ['question' => 'What is an artery?'])
        ->assertOk()
        ->json('data.conversationId');

    $assistantTurn = App\Models\ConversationMessage::query()
        ->where('conversation_id', $conversationId)
        ->where('role', 'assistant')
        ->firstOrFail();

    // The column and the key exist now, so landing retrieval is an insertion
    // rather than a migration (docs/architecture.md §8.2).
    expect($assistantTurn->metadata)->toHaveKey('source_ids')
        ->and($assistantTurn->metadata['source_ids'])->toBe([]);
});
