<?php

declare(strict_types=1);

namespace App\Infrastructure\VectorStore;

use App\Contracts\RetrievedChunk;
use App\Contracts\VectorStoreInterface;
use App\Models\KnowledgeChunk;
use Illuminate\Database\Eloquent\Builder;
use InvalidArgumentException;

/**
 * The default vector store (docs/architecture.md §8.1).
 *
 * Filters on the indexed columns in SQL, loads the surviving embeddings, and
 * computes cosine similarity in PHP. At MVP corpus size — a few thousand chunks,
 * narrowed by organ, structure and education level to tens or low hundreds of
 * rows — that is well under the 50 ms budget, needs no extension, no external
 * service and no credentials. It is the default precisely because a competition
 * demo that depends on a third-party index is a demo that can be taken down by
 * someone else's outage. If it stops being fast, the answer is
 * PineconeVectorStore, not a rewrite.
 *
 * It reads `knowledge_chunks` through Eloquent. Infrastructure normally stays
 * clear of Models (docs/architecture.md §4.2), but a MySQL-backed store *is*
 * that table, and the alternative — raw SQL — breaks invariant 6 to avoid
 * breaking a guideline. The dependency runs one way and no model knows this
 * class exists.
 */
final class MySqlVectorStore implements VectorStoreInterface
{
    private const NAME = 'mysql';

    /**
     * Filter keys backed by a real, indexed column (PRD §28). Anything else is
     * matched against the chunk's metadata JSON after the rows are loaded.
     */
    private const FILTER_COLUMNS = ['organ_id', 'structure_id', 'education_level', 'content_type'];

    /**
     * @param  list<array{
     *     id: string,
     *     vector: list<float>,
     *     content: string,
     *     metadata: array<string, scalar|null>
     * }>  $documents
     */
    public function upsert(array $documents): void
    {
        foreach ($documents as $document) {
            $address = KnowledgeChunk::parseVectorId($document['id']);

            if ($address === null) {
                // A programming error, not an operational one: ids in this
                // store are always `{document}:{index}` and are generated by
                // SyncVectorStore from a row that exists.
                throw new InvalidArgumentException(
                    'A ['.self::NAME."] vector id must be `document:index`, got [{$document['id']}]."
                );
            }

            [$documentId, $chunkIndex] = $address;

            // updateOrCreate on the unique (document_id, chunk_index) pair is
            // what makes upsert idempotent: re-ingesting a document rewrites
            // its chunks rather than doubling them.
            KnowledgeChunk::query()->updateOrCreate(
                ['document_id' => $documentId, 'chunk_index' => $chunkIndex],
                [
                    'content' => $document['content'],
                    'embedding' => $document['vector'],
                    'metadata' => $document['metadata'],
                    ...$this->columnsFrom($document['metadata']),
                ],
            );
        }
    }

    /**
     * @param  list<float>  $queryVector
     * @param  array<string, scalar|null>  $filters
     * @return list<RetrievedChunk>
     */
    public function search(array $queryVector, int $topK = 5, array $filters = []): array
    {
        if ($queryVector === [] || $topK < 1) {
            return [];
        }

        $rows = $this->filtered($filters)->get();

        // The query vector is the same on every iteration, so its magnitude is
        // too. Computing it inside cosineSimilarity squared 1,536 floats once
        // per surviving row — a third of the arithmetic, repeated a hundred
        // times over on the corpus §8.1 sizes for.
        $queryMagnitude = $this->magnitude($queryVector);

        // Filter keys that no column backs. Resolved once: when there are none,
        // which is the ordinary case, matchesMetadata never has to touch the
        // metadata JSON at all.
        $metadataFilters = array_diff_key($filters, array_flip(self::FILTER_COLUMNS));

        /** @var list<array{row: KnowledgeChunk, score: float}> $scored */
        $scored = [];

        foreach ($rows as $row) {
            if ($metadataFilters !== [] && ! $this->matchesMetadata($row, $metadataFilters)) {
                continue;
            }

            $scored[] = [
                'row' => $row,
                'score' => $this->cosineSimilarity(
                    $queryVector,
                    $row->embedding ?? [],
                    magnitudeA: $queryMagnitude,
                ),
            ];
        }

        // Sort the scores, then build results for the handful that survive.
        // Constructing a RetrievedChunk per row meant reading the citation and
        // decoding the metadata JSON for every candidate, and topK is five —
        // ninety-five of every hundred were built only to be sliced away.
        // PHP's sort is stable, so equal scores keep the order the rows arrived
        // in, exactly as before.
        usort($scored, static fn (array $a, array $b): int => $b['score'] <=> $a['score']);

        return array_map(
            fn (array $candidate): RetrievedChunk => new RetrievedChunk(
                id: $candidate['row']->vectorId(),
                content: $candidate['row']->content,
                score: $candidate['score'],
                sourceTitle: $this->sourceTitleFor($candidate['row']),
                metadata: $this->metadataFor($candidate['row']),
            ),
            array_slice($scored, 0, $topK),
        );
    }

    /**
     * @param  list<string>  $ids
     */
    public function delete(array $ids): void
    {
        foreach ($ids as $id) {
            $address = KnowledgeChunk::parseVectorId($id);

            // Unknown ids are ignored, not an error: a delete replaying after a
            // document was already removed must not fail the job.
            if ($address === null) {
                continue;
            }

            KnowledgeChunk::query()
                ->where('document_id', $address[0])
                ->where('chunk_index', $address[1])
                ->delete();
        }
    }

    /**
     * Rows that survive the indexed filters.
     *
     * `whereNotNull('embedding')` is part of the filter, not an optimisation: a
     * chunk written by ProcessKnowledgeDocument but not yet embedded would
     * otherwise score 0.0 and pad the result set of a small corpus.
     *
     * @param  array<string, scalar|null>  $filters
     * @return Builder<KnowledgeChunk>
     */
    private function filtered(array $filters): Builder
    {
        $query = KnowledgeChunk::query()
            ->whereNotNull('embedding')
            // The citation. Eager-loaded because scoring iterates every
            // surviving row, and a lazy read here would be one query per chunk.
            ->with('document:id,title')
            ->select(['id', 'document_id', 'chunk_index', 'content', 'embedding', 'metadata']);

        foreach ($filters as $key => $value) {
            if (in_array($key, self::FILTER_COLUMNS, true)) {
                $query->where($key, $value);
            }
        }

        return $query;
    }

    /**
     * Apply the filter keys that no column backs against the chunk's metadata.
     *
     * Still "before scoring", as the contract requires — just in PHP, because
     * a JSON extract cannot use an index and the alternative is a filter key
     * silently doing nothing.
     *
     * The caller passes only the non-column keys and skips the call entirely
     * when there are none, so an ordinary organ-filtered search never decodes
     * the metadata JSON of a row it is merely scoring.
     *
     * @param  array<string, scalar|null>  $metadataFilters
     */
    private function matchesMetadata(KnowledgeChunk $chunk, array $metadataFilters): bool
    {
        $metadata = $chunk->metadata ?? [];

        foreach ($metadataFilters as $key => $value) {
            if (($metadata[$key] ?? null) !== $value) {
                return false;
            }
        }

        return true;
    }

    /**
     * The columns mirrored out of a document's metadata so they can be indexed.
     *
     * @param  array<string, scalar|null>  $metadata
     * @return array<string, scalar|null>
     */
    private function columnsFrom(array $metadata): array
    {
        $columns = [];

        foreach (self::FILTER_COLUMNS as $column) {
            $columns[$column] = $metadata[$column] ?? null;
        }

        return $columns;
    }

    /**
     * What the student sees as the citation.
     *
     * The document's current title wins over the copy in the chunk's metadata:
     * an admin correcting a title should not have to re-index to fix every
     * citation that quotes it.
     */
    private function sourceTitleFor(KnowledgeChunk $chunk): string
    {
        $title = $chunk->document->title;

        if ($title !== '') {
            return $title;
        }

        $metadata = $chunk->metadata ?? [];

        return (string) ($metadata['source_title'] ?? 'Untitled source');
    }

    /**
     * @return array<string, scalar|null>
     */
    private function metadataFor(KnowledgeChunk $chunk): array
    {
        /** @var array<string, scalar|null> $metadata */
        $metadata = $chunk->metadata ?? [];

        return $metadata;
    }

    /**
     * Euclidean length of a vector.
     *
     * @param  list<float>  $vector
     */
    private function magnitude(array $vector): float
    {
        $total = 0.0;

        foreach ($vector as $value) {
            $total += $value * $value;
        }

        return sqrt($total);
    }

    /**
     * @param  list<float>  $a
     * @param  list<float>  $b
     * @param  float  $magnitudeA  `$a`'s Euclidean length, hoisted out of the
     *                             caller's loop because `$a` is the query
     *                             vector and does not change between chunks.
     */
    private function cosineSimilarity(array $a, array $b, float $magnitudeA): float
    {
        // Mismatched dimensions mean the corpus was embedded with a different
        // model than the query. Scoring it anyway would rank garbage highly, so
        // treat it as "no similarity" and let RetrievalService's min_score drop
        // it — the same rule NullVectorStore applies, and the shared contract
        // suite asserts both.
        if ($a === [] || count($a) !== count($b)) {
            return 0.0;
        }

        $dot = 0.0;
        $magnitudeB = 0.0;

        // `$b[$index]` read once into a local, and squared by multiplication
        // rather than `** 2`. Over 1,536 dimensions and a hundred candidates
        // that is 150,000 array reads and 150,000 pow calls removed, and it
        // halves the cost of this loop — measured, not assumed.
        foreach ($a as $index => $value) {
            $component = $b[$index];
            $dot += $value * $component;
            $magnitudeB += $component * $component;
        }

        if ($magnitudeA === 0.0 || $magnitudeB === 0.0) {
            return 0.0;
        }

        // Identical arithmetic to sqrt($sumOfSquaresA) * sqrt($magnitudeB):
        // $magnitudeA arrives already rooted, so the same two roots are
        // multiplied and the scores are bit-for-bit what they were.
        return $dot / ($magnitudeA * sqrt($magnitudeB));
    }
}
