<?php

declare(strict_types=1);

namespace App\Infrastructure\VectorStore;

use App\Contracts\RetrievedChunk;
use App\Contracts\VectorStoreInterface;
use App\Models\KnowledgeChunk;
use Illuminate\Database\Eloquent\Builder;
use InvalidArgumentException;

/**
 * The default vector store (docs/architecture.md §8.1).
 *
 * Filters on the indexed columns in SQL, loads the surviving embeddings, and
 * computes cosine similarity in PHP. At MVP corpus size — a few thousand chunks,
 * narrowed by organ, structure and education level to tens or low hundreds of
 * rows — that is well under the 50 ms budget, needs no extension, no external
 * service and no credentials. It is the default precisely because a competition
 * demo that depends on a third-party index is a demo that can be taken down by
 * someone else's outage. If it stops being fast, the answer is
 * PineconeVectorStore, not a rewrite.
 *
 * It reads `knowledge_chunks` through Eloquent. Infrastructure normally stays
 * clear of Models (docs/architecture.md §4.2), but a MySQL-backed store *is*
 * that table, and the alternative — raw SQL — breaks invariant 6 to avoid
 * breaking a guideline. The dependency runs one way and no model knows this
 * class exists.
 */
final class MySqlVectorStore implements VectorStoreInterface
{
    private const NAME = 'mysql';

    /**
     * Filter keys backed by a real, indexed column (PRD §28). Anything else is
     * matched against the chunk's metadata JSON after the rows are loaded.
     */
    private const FILTER_COLUMNS = ['organ_id', 'structure_id', 'education_level', 'content_type'];

    /**
     * @param  list<array{
     *     id: string,
     *     vector: list<float>,
     *     content: string,
     *     metadata: array<string, scalar|null>
     * }>  $documents
     */
    public function upsert(array $documents): void
    {
        foreach ($documents as $document) {
            $address = KnowledgeChunk::parseVectorId($document['id']);

            if ($address === null) {
                // A programming error, not an operational one: ids in this
                // store are always `{document}:{index}` and are generated by
                // SyncVectorStore from a row that exists.
                throw new InvalidArgumentException(
                    'A ['.self::NAME."] vector id must be `document:index`, got [{$document['id']}]."
                );
            }

            [$documentId, $chunkIndex] = $address;

            // updateOrCreate on the unique (document_id, chunk_index) pair is
            // what makes upsert idempotent: re-ingesting a document rewrites
            // its chunks rather than doubling them.
            KnowledgeChunk::query()->updateOrCreate(
                ['document_id' => $documentId, 'chunk_index' => $chunkIndex],
                [
                    'content' => $document['content'],
                    'embedding' => $document['vector'],
                    'metadata' => $document['metadata'],
                    ...$this->columnsFrom($document['metadata']),
                ],
            );
        }
    }

    /**
     * @param  list<float>  $queryVector
     * @param  array<string, scalar|null>  $filters
     * @return list<RetrievedChunk>
     */
    public function search(array $queryVector, int $topK = 5, array $filters = []): array
    {
        if ($queryVector === [] || $topK < 1) {
            return [];
        }

        $rows = $this->filtered($filters)->get();

        $scored = [];

        foreach ($rows as $row) {
            if (! $this->matchesMetadata($row, $filters)) {
                continue;
            }

            $scored[] = new RetrievedChunk(
                id: $row->vectorId(),
                content: $row->content,
                score: $this->cosineSimilarity($queryVector, $row->embedding ?? []),
                sourceTitle: $this->sourceTitleFor($row),
                metadata: $this->metadataFor($row),
            );
        }

        usort($scored, static fn (RetrievedChunk $a, RetrievedChunk $b): int => $b->score <=> $a->score);

        return array_slice($scored, 0, $topK);
    }

    /**
     * @param  list<string>  $ids
     */
    public function delete(array $ids): void
    {
        foreach ($ids as $id) {
            $address = KnowledgeChunk::parseVectorId($id);

            // Unknown ids are ignored, not an error: a delete replaying after a
            // document was already removed must not fail the job.
            if ($address === null) {
                continue;
            }

            KnowledgeChunk::query()
                ->where('document_id', $address[0])
                ->where('chunk_index', $address[1])
                ->delete();
        }
    }

    /**
     * Rows that survive the indexed filters.
     *
     * `whereNotNull('embedding')` is part of the filter, not an optimisation: a
     * chunk written by ProcessKnowledgeDocument but not yet embedded would
     * otherwise score 0.0 and pad the result set of a small corpus.
     *
     * @param  array<string, scalar|null>  $filters
     * @return Builder<KnowledgeChunk>
     */
    private function filtered(array $filters): Builder
    {
        $query = KnowledgeChunk::query()
            ->whereNotNull('embedding')
            // The citation. Eager-loaded because scoring iterates every
            // surviving row, and a lazy read here would be one query per chunk.
            ->with('document:id,title')
            ->select(['id', 'document_id', 'chunk_index', 'content', 'embedding', 'metadata']);

        foreach ($filters as $key => $value) {
            if (in_array($key, self::FILTER_COLUMNS, true)) {
                $query->where($key, $value);
            }
        }

        return $query;
    }

    /**
     * Apply any filter key that is not a column against the chunk's metadata.
     *
     * Still "before scoring", as the contract requires — just in PHP, because
     * a JSON extract cannot use an index and the alternative is a filter key
     * silently doing nothing.
     *
     * @param  array<string, scalar|null>  $filters
     */
    private function matchesMetadata(KnowledgeChunk $chunk, array $filters): bool
    {
        $metadata = $chunk->metadata ?? [];

        foreach ($filters as $key => $value) {
            if (in_array($key, self::FILTER_COLUMNS, true)) {
                continue;
            }

            if (($metadata[$key] ?? null) !== $value) {
                return false;
            }
        }

        return true;
    }

    /**
     * The columns mirrored out of a document's metadata so they can be indexed.
     *
     * @param  array<string, scalar|null>  $metadata
     * @return array<string, scalar|null>
     */
    private function columnsFrom(array $metadata): array
    {
        $columns = [];

        foreach (self::FILTER_COLUMNS as $column) {
            $columns[$column] = $metadata[$column] ?? null;
        }

        return $columns;
    }

    /**
     * What the student sees as the citation.
     *
     * The document's current title wins over the copy in the chunk's metadata:
     * an admin correcting a title should not have to re-index to fix every
     * citation that quotes it.
     */
    private function sourceTitleFor(KnowledgeChunk $chunk): string
    {
        $title = $chunk->document->title;

        if ($title !== '') {
            return $title;
        }

        $metadata = $chunk->metadata ?? [];

        return (string) ($metadata['source_title'] ?? 'Untitled source');
    }

    /**
     * @return array<string, scalar|null>
     */
    private function metadataFor(KnowledgeChunk $chunk): array
    {
        /** @var array<string, scalar|null> $metadata */
        $metadata = $chunk->metadata ?? [];

        return $metadata;
    }

    /**
     * @param  list<float>  $a
     * @param  list<float>  $b
     */
    private function cosineSimilarity(array $a, array $b): float
    {
        // Mismatched dimensions mean the corpus was embedded with a different
        // model than the query. Scoring it anyway would rank garbage highly, so
        // treat it as "no similarity" and let RetrievalService's min_score drop
        // it — the same rule NullVectorStore applies, and the shared contract
        // suite asserts both.
        if ($a === [] || count($a) !== count($b)) {
            return 0.0;
        }

        $dot = 0.0;
        $magnitudeA = 0.0;
        $magnitudeB = 0.0;

        foreach ($a as $index => $value) {
            $dot += $value * $b[$index];
            $magnitudeA += $value ** 2;
            $magnitudeB += $b[$index] ** 2;
        }

        if ($magnitudeA === 0.0 || $magnitudeB === 0.0) {
            return 0.0;
        }

        return $dot / (sqrt($magnitudeA) * sqrt($magnitudeB));
    }
}
