<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * Whether a lesson is visible to students.
 *
 * Mirrors OrganStatus deliberately — same two states, same default, same
 * meaning — so an admin publishing content (F13) learns one rule rather than
 * two. `draft` is the migration default, so a lesson imported or generated by
 * a tool is invisible until someone publishes it on purpose.
 */
enum LessonStatus: string
{
    case Draft = 'draft';
    case Published = 'published';

    public function label(): string
    {
        return match ($this) {
            self::Draft => 'Draft',
            self::Published => 'Published',
        };
    }

    /**
     * @return list<string>
     */
    public static function values(): array
    {
        return array_map(static fn (self $case): string => $case->value, self::cases());
    }
}
