<?php

declare(strict_types=1);

namespace App\Providers;

use App\Contracts\AIProviderInterface;
use App\Contracts\VectorStoreInterface;
use App\Infrastructure\AI\NullProvider;
use App\Infrastructure\VectorStore\NullVectorStore;
use App\Models\User;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\ServiceProvider;
use Illuminate\Validation\Rules\Password;

/**
 * Platform-wide bindings and defaults.
 *
 * OWNED BY HANDOVER 01. Features do not edit this file — a feature that needs
 * container bindings registers its own provider (AiServiceProvider,
 * RagServiceProvider) and adds it to bootstrap/providers.php
 * (docs/feature-plan.md §7.3).
 */
final class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->registerBaselineAiBindings();
    }

    public function boot(): void
    {
        $this->enforceModelStrictness();
        $this->configurePasswordPolicy();
        $this->configureRateLimiting();
        $this->configureHorizonAccess();
    }

    /**
     * Bind both contracts to their null implementations.
     *
     * These are BASELINE bindings, not the final word. Handover 08's
     * AiServiceProvider and Handover 11's RagServiceProvider register after
     * this provider and rebind the same interfaces to the real implementations
     * selected by config('ai.provider') and config('ai.vector_store'); a later
     * bind() wins, which is exactly how a feature overrides the platform
     * without editing this file.
     *
     * Binding something here means the container always resolves: a page that
     * merely type-hints one of these does not fatal before its owning feature
     * exists, and the whole test suite gets a deterministic, network-free
     * implementation for free (docs/engineering.md §9).
     */
    private function registerBaselineAiBindings(): void
    {
        $this->app->singleton(AIProviderInterface::class, function (): NullProvider {
            $store = (string) config('ai.vector_store', 'null');

            return new NullProvider(
                dimensions: (int) config("ai.vector_stores.{$store}.dimensions", 1536),
            );
        });

        // Singleton because NullVectorStore holds its documents in memory;
        // a fresh instance per resolve would lose everything just upserted.
        $this->app->singleton(VectorStoreInterface::class, NullVectorStore::class);
    }

    /**
     * Turn silent data bugs into loud ones outside production.
     *
     * preventLazyLoading is the N+1 detector docs/engineering.md §10 asks for:
     * a relation touched in a loop without with() throws in development and CI
     * instead of quietly issuing a hundred queries that a judge would see as a
     * slow demo.
     */
    private function enforceModelStrictness(): void
    {
        Model::shouldBeStrict(! $this->app->isProduction());
        Model::unguard(false);
    }

    private function configurePasswordPolicy(): void
    {
        Password::defaults(function (): Password {
            // Length over composition rules: NIST 800-63B, and it is the
            // policy 14-year-olds are most likely to actually comply with
            // rather than write on a sticky note.
            $rule = Password::min(10);

            return $this->app->isProduction()
                ? $rule->uncompromised()
                : $rule;
        });
    }

    private function configureRateLimiting(): void
    {
        RateLimiter::for('api', fn (Request $request): Limit => $request->user() !== null
            ? Limit::perMinute(120)->by((string) $request->user()->getAuthIdentifier())
            : Limit::perMinute(30)->by((string) $request->ip()));

        // Named here so every AI endpoint added by Handovers 08/11/12 gets the
        // same limit from config without re-deriving one. Rate limits ship with
        // the endpoint, not after it (docs/engineering.md §10).
        RateLimiter::for('ai', fn (Request $request): Limit => Limit::perMinute(
            (int) config('ai.limits.requests_per_minute', 10)
        )->by((string) ($request->user()?->getAuthIdentifier() ?? $request->ip())));
    }

    /**
     * The Horizon dashboard exposes queue payloads, failure traces, and
     * throughput. Admins only, in every environment except local.
     */
    private function configureHorizonAccess(): void
    {
        Gate::define('viewHorizon', static fn (User $user): bool => $user->isAdmin());
    }
}
